tt: add template for Tarantool DB
tarantool/tt pull request #1005
Opened 2024-11-11 13:51 UTC by Satbek

tt create tarantool_db --name myapp

2024-11-14 11:50 UTC, dmyger approved these changes

2024-11-14 12:00 UTC, DerekBum approved these changes

2024-11-14 12:00 UTC, DerekBum commented on cli/create/builtin_templates/templates/tarantool_db/Makefile
Missing newline at the end of this file.

2024-11-15 08:04 UTC, a1div0 requested changes

2024-11-15 08:05 UTC, a1div0 commented on cli/create/builtin_templates/templates/tarantool_db/cluster/docker-compose.yml
> +        && tt migrations apply http://etcd:2379/tdb \
(тут ничего делать не надо)

2024-11-18 12:21 UTC, a1div0 approved these changes

2024-11-19 09:07 UTC, oleg-jukovec commented
Please, squash commits.

2024-11-19 09:29 UTC, oleg-jukovec requested changes
Если честно, то я не понимаю зачем tt тут в принципе, если он никак не используется. Это очень и очень странный шаблон приложения для tt, которое не является приложением для tt.

Вероятно, нам в принципе не нужен built-in шаблон такого рода в tt и он может просто поставляться вместе с tarantooldb.

2024-11-19 09:29 UTC, oleg-jukovec commented on cli/cmd/create.go
> +	$ tt create tarantool_db --name myapp`,
```suggestion
    $ tt create vshard_cluster --name cluster_app

# Create Tarantool DB application.

    $ tt create tarantool_db --name myapp`,
```

2024-11-19 09:29 UTC, oleg-jukovec commented on cli/create/builtin_templates/templates/tarantool_db/README.md.tt.template
> +```
А почему тут русский? Для консистентности с остальными командами хотелось бы английский.

Плюс какую-то часть информации можно вывести сразу после создания шаблона, как это сделано, скажем, в cartridge:

```
tt create cartridge --name foo
   • Creating application in "/tmp/tt/foo"
   • Using built-in 'cartridge' template.
Cluster cookie (default: secret-cluster-cookie): 
   • Application 'foo' created successfully
What's next?
Build and start 'foo' application:
    $ tt build foo
    $ tt start foo

To bootstrap vshard run the following command:
    $ tt cartridge replicasets setup --bootstrap-vshard --name foo --run-dir var/run/foo
```

2024-11-19 09:58 UTC, a1div0 commented
> Вероятно, нам в принципе не нужен built-in шаблон такого рода в tt и он может просто поставляться вместе с tarantooldb.

Привет!
Поставка tarantooldb предназначена для другой команды. У пользователя не будет на руках дистрибутива. Потому что он ему не нужен. На данный момент пользователю ничего не нужно скачивать.

Пользователь может выборочно скачать tt-ee, может скачать отдельно документацию.

Мы хотим добавить это в tt для удобства пользователя. Чтобы ему не нужно было ничего больше скачивать или клонировать, или копировать, или устанавливать, или распаковывать. У него будет единое средство, которое позволяет делать всякое с кластером tarantooldb. Вот такое видение.

Давайте обсудим

2024-11-20 10:19 UTC, closed without merging