modules: tt.yaml modules/directory support list
tarantool/tt pull request #1032
Opened 2024-11-22 15:32 UTC by dmyger

The logic of working with configuration file tt.yaml has been updated,
now  modules/directory can be specified both as a single line and
as a list.

2024-11-26 16:42 UTC, oleg-jukovec requested changes
Please, add a `Changed` entry into the CHANGELOG.md.

2024-11-26 17:05 UTC, dmyger commented
> CHANGELOG.md

Done.

2024-11-26 18:30 UTC, patapenka-alexey approved these changes
Thank you for the patch. LGTM.

2024-11-26 18:40 UTC, oleg-jukovec commented on CHANGELOG.md
> +- `tt.yaml` allow specify a list of modules directories.
```suggestion
- `tt.yaml`: allows to specify a list of modules directories.
```

2024-11-27 14:03 UTC, oleg-jukovec approved these changes

2024-11-28 09:04 UTC, oleg-jukovec commented
Please, rebase on the master branch & it could be merged.

2024-11-28 11:55 UTC, oleg-jukovec commented
config: Find yaml config if input no extension -> config: find yaml config if input no extension

2024-11-28 11:57 UTC, oleg-jukovec commented
I'm sorry, but we forgot about @TarantoolBot here. Please, add a description to the commit and the PR messages, see:
https://github.com/tarantool/tt/pull/1030
https://github.com/tarantool/tt/pull/1026

2024-11-28 13:57 UTC, oleg-jukovec approved these changes

2024-11-28 14:27 UTC, merged