Dmyger/gh-1014-prepare-modules-list
tarantool/tt pull request #1041
Opened 2024-11-28 12:46 UTC by dmyger

Find possible modules by manifest.yaml or main executable.

Closes #1014

2024-11-28 14:14 UTC, oleg-jukovec approved these changes
I don't like the idea of ​​implementing something without an ability to test it. In the future, we need to split an issues or API design taking into account that you will need to write tests at each step

Ok now.

2024-11-28 14:16 UTC, oleg-jukovec requested changes
There is something broken in tests.

2024-12-13 13:04 UTC, dmyger commented on cli/modules/modules.go
> +	// }
Add a comment to don't forget adjust the commented code.

2025-03-21 08:37 UTC, oleg-jukovec requested changes
Tests are red.

2025-03-21 08:37 UTC, oleg-jukovec commented on cli/cmd/completion.go
> +			description, err := modules.GetExternalModuleDescription(manifest.Main)
Why this renamed, but modulesInfo is not?

2025-03-21 08:37 UTC, oleg-jukovec commented on cli/modules/modules.go
> +	return mf, nil
We need to enable some linter...
```suggestion
func readManifest(dir string, manifest string) (Manifest, error) {
	mf := Manifest{}
	data, err := os.ReadFile(manifest)
	if err != nil {
		return mf, fmt.Errorf("failed to read manifest: %s", err)
	}

	if err := yaml.Unmarshal(data, &mf); err != nil {
		return mf, fmt.Errorf("failed to parse manifest: %s", err)
	}

	mf.Main, err = exec.LookPath(filepath.Join(dir, mf.Main))
	if err != nil {
		return mf, fmt.Errorf("failed to find module executable: %s", err)
	}

	if mf.Version == "" {
		return mf, fmt.Errorf("version field is mandatory for module Manifest")
	}
	if mf.Help == "" {
		return mf, fmt.Errorf("help field is mandatory for module Manifest")
	}

	return mf, nil
```

2025-03-21 08:37 UTC, oleg-jukovec commented on cli/modules/modules.go
> +	return dirs, nil
```suggestion

	entries = slices.DeleteFunc(entries, func(e os.DirEntry) bool {
		return !e.IsDir()
	})

	slices.SortFunc(entries, func(a, b os.DirEntry) int {
		return strings.Compare(a.Name(), b.Name())
	})

	dirs := make([]string, 0, len(entries))
	for _, e := range entries {
		dirs = append(dirs, e.Name())
	}

	return dirs, nil
```

2025-03-21 08:37 UTC, oleg-jukovec commented on cli/modules/modules.go
> +		cnt_modules := 0
etc

2025-03-21 15:13 UTC, dmyger commented on cli/cmd/completion.go
> +			description, err := modules.GetExternalModuleDescription(manifest.Main)
Don't see what is wrong with a "modules info" name?
This name reflects the purpose of map to keep information about modules.

2025-03-25 08:56 UTC, oleg-jukovec approved these changes

2025-03-25 11:34 UTC, patapenka-alexey commented on cli/modules/modules.go
> +				cnt_modules += 1
```suggestion
				cnt_modules++
```
Up to you.

2025-03-25 11:35 UTC, patapenka-alexey commented on cli/modules/modules.go
> +				cnt_modules += 1
Please, update commit messages and I will approve.
```md
Closes #1015
Closes #TNTP-1804
```

2025-03-25 11:36 UTC, patapenka-alexey commented
Please, update commit messages and I will approve.
```md
Closes #1015
Closes #TNTP-1804
```

2025-03-25 12:35 UTC, dmyger commented on cli/modules/modules.go
> +				cnt_modules += 1
Removed, unused.

2025-03-25 12:39 UTC, dmyger commented
> Please, update commit messages

Done.

2025-03-31 12:50 UTC, patapenka-alexey approved these changes

2025-03-31 14:40 UTC, merged