connector: replace connector by go-tarantool
tarantool/tt pull request #176
Opened 2022-10-07 06:44 UTC by oleg-jukovec

The patch replaces [FZambia/tarantool](https://github.com/FZambia/tarantool) connector by [tarantool/go-tarantool](https://github.com/tarantool/go-tarantool/).

It also adds a unit test with Tarantool instance integration. To run these tests, you need to use 'unitfull' Mage's target.

Closes #54

2022-10-18 12:11 UTC, LeonidVas requested changes
Hi! Thank you for the patchset.
See several comments bellow.

2022-10-18 12:11 UTC, LeonidVas commented on magefile.go
> +	return sh.RunV(goExecutableName, "test", fmt.Sprintf("%s/...", packagePath))
Maybe + "-tags", "integration" ?

2022-10-18 17:51 UTC, oleg-jukovec commented on cli/connector/binary.go
> +func (c *BinaryConnect) Eval(expr string, args []interface{},
It is an idiomatic naming for receivers:
https://gist.github.com/adamveld12/c0d9f0d5f0e1fba1e551#receiver-names

But it is not a strict rule, so no problems - I will rename it.

2022-10-18 17:58 UTC, oleg-jukovec commented on cli/connector/binary.go
> +	fut := c.conn.Do(evalReq)
No real need, but shortened names are fine (even welcome) in Golang. For example, see the code in the file:
https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/net/http/client.go;l=203

But for me it is not very important, I can use full names if necessary.

2022-10-19 09:16 UTC, oleg-jukovec commented on cli/connector/connector.go
> +type ConnectCloser interface {
I renamed the interfaces:

* Connector -> Evaler
* ConnectCloser -> Connector

and correct the description. It looks a little easier to get the idea this way.

The idea is same as @psergee describe + it's easier to write tests. See the second commit:

```connect: add unit-test for change language```

It shows the idea in action.

2022-10-19 09:36 UTC, oleg-jukovec commented on magefile.go
> +	return sh.RunV(goExecutableName, "test", fmt.Sprintf("%s/...", packagePath))
You're right, thank you. Fixed.

2022-10-19 09:36 UTC, oleg-jukovec commented on cli/connector/connector.go
> +			SkipSchema: true, // we don't need a schema for eval requests
Thanks! I missed the commit on overview. Fixed.

2022-10-19 09:37 UTC, oleg-jukovec commented on cli/connector/binary.go
> +			timeout = time.Duration(1<<63 - 1)
Good idea, replaced!

2022-10-19 09:37 UTC, oleg-jukovec commented on cli/connector/binary.go
> +func (c *BinaryConnect) Eval(expr string, args []interface{},
Updated.

2022-10-19 09:38 UTC, oleg-jukovec commented on cli/connector/binary.go
> +type BinaryConnect struct {
To separate the interface names from the implementation. But there are no strict rules for this in Golang, so renamed:

* BinaryConnect -> BinaryConnector
* TextConnect -> TextConnector

2022-10-19 09:40 UTC, oleg-jukovec commented on cli/connector/binary.go
> +// NewBinaryConnect creates a new BinaryConnect object. The object will close
I've updated NewBinaryConnector/NewTextConnector/BinaryConnector.Close/TextConnector.Close description. I hope it will be clearer.

2022-10-19 11:45 UTC, LeonidVas commented on cli/connector/binary.go
> +func (c *BinaryConnect) Eval(expr string, args []interface{},
"one-letter names in short loops" - generally ok.
The problem with short names is that they do not describe the object and (more important) they are not convenient to search in code by `Ctrl+F`.

2022-10-19 11:49 UTC, psergee approved these changes

2022-10-19 12:04 UTC, LeonidVas approved these changes
LGTM

2022-10-19 12:22 UTC, oleg-jukovec commented on cli/connect/connect.go
> +func getConnOpts(connString string, cmdCtx *cmdcontext.CmdCtx) connector.ConnectOpts {
Thank you, updated.

2022-10-19 12:23 UTC, oleg-jukovec commented on cli/connector/binary.go
> +	fut := c.conn.Do(evalReq)
Updated.

2022-10-19 13:04 UTC, merged