tt: re-work executables search logic
tarantool/tt pull request #177
Opened 2022-10-07 14:02 UTC by psergee

- Verbose mode support is added. Use -V to see debug log output.
- Only one of -S, -L, --cfg options can be specified.
- If tarantool executable is missing in bin_dir, a default from /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/psergee/go/bin:/home/psergee/work/tarantool/build/extra/dist/
will be used if available.
- If tt executable is missing in bin_dir, current process is used.
- System config is not loaded if -L of --cfg options are specified and
local config is missing.

Closes #174

2022-10-09 14:20 UTC, better0fdead requested changes
Hi, thanks for patch. Can you pls add description for the first commit. (smth like ' Added verbose flag. It enables debug log output.')

2022-10-09 15:49 UTC, psergee commented on cli/configure/configure.go
> +			return fmt.Errorf(`Found Tarantool binary '%s' isn't executable: %s`,
Agree. But this will be inconsistent with other error messages. I believe, all error strings in tt code must be fixed under separate PR.

2022-10-09 15:49 UTC, psergee commented on cli/configure/configure.go
> +		return fmt.Errorf("Failed to get access to Tarantool binary file: %s", err)
Agree. But this will be inconsistent with other error messages. I believe, all error strings in tt code must be fixed under separate PR.

2022-10-09 15:49 UTC, psergee commented on cli/configure/configure.go
> +					return fmt.Errorf("Failed to find Tarantool CLI config for '%s'",
Agree. But this will be inconsistent with other error messages. I believe, all error strings in tt code must be fixed under separate PR.

2022-10-09 15:49 UTC, psergee commented on cli/configure/configure.go
> +			return fmt.Errorf(`Failed to get absolute path to local directory: %s`, err)
Agree. But this will be inconsistent with other error messages. I believe, all error strings in tt code must be fixed under separate PR.

2022-10-09 15:50 UTC, psergee commented on cli/configure/configure.go
> +			return fmt.Errorf(`Failed to change working directory: %s`, err)
Agree. But this will be inconsistent with other error messages. I believe, all error strings in tt code must be fixed under separate PR.

2022-10-09 15:53 UTC, psergee commented
> Hi, thanks for patch. Can you pls add description for the first commit. (smth like ' added verbose flag. It enables debug log output.')

Sure. Verbose mode description is added to the commit message.

2022-10-09 20:28 UTC, better0fdead approved these changes
LGTM

2022-10-11 11:16 UTC, 0x501D commented on cli/configure/configure.go
> +	systemConfigDirEnvName = "SYSTEM_CONFIG_DIR"
Please use TT prefix for variables.

2022-10-11 11:33 UTC, 0x501D approved these changes
LGTM

2022-10-11 12:09 UTC, psergee commented on cli/configure/configure.go
> +	systemConfigDirEnvName = "SYSTEM_CONFIG_DIR"
Done.

2022-10-11 23:26 UTC, merged