create: added support of built-in templates
tarantool/tt pull request #201
Opened 2022-10-25 18:26 UTC by psergee

First added built-in template is cartridge application template.

Closes #195

2022-11-08 14:11 UTC, 0x501D approved these changes
LGTM

2022-11-08 14:45 UTC, LeonidVas requested changes
Hi! Thank you for the patchset.
Good work.

I looked at this patchset not detail and had a couple of questions. Check them out, and I'll continue to look into the patchset.

2022-11-08 14:45 UTC, LeonidVas commented on cli/create/builtin_templates/templates/cartridge/.cartridge.yml
> +stateboard: true # If no arguments are supplied, --stateboard flag is true
What does the `stateboard` flag mean?
We start the application by `tt start` command, not `cartridge start`.

2022-11-08 14:45 UTC, LeonidVas commented on cli/create/builtin_templates/templates/cartridge/.editorconfig
> +# top-most EditorConfig file
What is this file used for?

2022-11-08 14:45 UTC, LeonidVas commented on cli/create/builtin_templates/templates/cartridge/.cartridge.yml
> +# cfg: path-to-cfg-file
`log-dir`, `run-diir`... must be specified in the `tarantool.yaml`. Or no?

2022-11-08 14:45 UTC, LeonidVas commented on cli/create/builtin_templates/templates/cartridge/.luacheckrc
> +include_files = {'**/*.lua', '*.luacheckrc', '*.rockspec'}
Like with `git`, move the addition of files for `luachek` to a separate commit.

2022-11-08 14:45 UTC, LeonidVas commented on cli/create/builtin_templates/templates/cartridge/README.md.tt.template
> +# Simple Tarantool Cartridge-based application
Git stuff.

2022-11-08 14:45 UTC, LeonidVas commented on cli/create/builtin_templates/templates/cartridge/test/helper.lua
> +-- This file is required automatically by luatest.
The stuff that adds the test environment for the cartridge application, I suggest that it also be moved to a separate commit.

2022-11-08 17:15 UTC, psergee commented on cli/create/builtin_templates/templates/cartridge/app/roles/custom.lua
> +    -- if opts.is_master then
This commented code is to show that opts table has is_master flag.

2022-11-08 17:48 UTC, psergee commented on cli/create/builtin_templates/templates/cartridge/stateboard.init.lua
> +#!/usr/bin/env tarantool
This is standard construct for all scripts. I'd like to leave it, because this script can be used without tt.

2022-11-15 14:08 UTC, LeonidVas approved these changes
LGTM.

2022-11-15 14:22 UTC, merged