Proccesed error when no init file is specified
tarantool/tt pull request #50
Opened 2022-04-14 00:53 UTC by better0fdead

Previously if no init file was specifed output was:Currently, you can specify only one instance at a time
which is incorrect. So i proccesed it.

2022-04-14 00:57 UTC, better0fdead commented
I am not sure why 1 check failed, I think it is on gh side bcs other checks passed and fix has nothing to do with log rotation.

2022-04-14 07:45 UTC, LeonidVas commented
> I am not sure why 1 check failed, I think it is on gh side bcs other checks passed and fix has nothing to do with log rotation.

It's like a race in the test.

2022-04-14 08:13 UTC, LeonidVas requested changes
Hi! Thank you for the patch.
I don't think that it's useful, but I don't mind.
See https://github.com/tarantool/tarantool/wiki/Code-review-procedure#commit-message 
> Commit message should fit 72 symbols line width.

Add <submodule> (`running: ....`).
init file -> instance file
Proccesed -> Processed
Processed -> `add processing` (It's convenient when the title sounds like a command and in some clever book was it written to do so)
output was:Currently, you can specify only one instance at a time which is incorrect ->  output was: "Currently, you can specify only one instance at a time which is incorrect"
So i -> So I

2022-04-15 08:29 UTC, LeonidVas approved these changes

2022-04-15 08:31 UTC, merged