tt: add compatibility of pack command with the cartridge cli pack
tarantool/tt pull request #529
Opened 2023-07-12 17:03 UTC by DerekBum

New flag `--cartridge-compat` added for pack command, that fixes some differences between `tt pack` and `cartridge-cli pack`.
It solves naming differences (of resulting packages and applications in them). Also `VERSION` and `VERSION.lua` files will be present in resulting bundle.

Closes #504

2023-07-13 10:06 UTC, psergee reviewed
Thanks for the patch.
Please, add integration tests for pack with new option. Scenarios to check:
- Pack single app. Should work.
- Pack multiple apps in instances enabled, but only one specified in --app-list. Should work.
- Pack multiple apps. Shouldn't work. Cannot pack multiple apps in compat mode.
- Pack app from current directory (`instances_enabled` is set to '.')

2023-07-13 10:06 UTC, psergee commented on cli/pack/common.go
> +			// We need more info for generating VERSION and VERSION.lua files
Which info?

2023-07-13 10:09 UTC, psergee commented on cli/cmd/pack.go
> +	packCmd.Flags().BoolVar(&packCtx.CartridgeCompat, "cartridge-compat", false,
Do we check somewhere this is valid only for tgz pack type?

2023-07-13 11:07 UTC, DerekBum commented on cli/pack/common.go
> +		appName = filepath.Base(appPath)
Yes, and there is an unit test about that. Suppose we have applications `app1.lua` and `app3.lua`, and `app3.lua` symlinked to `app1.lua`. 
So when we copying those apps, we want to see only one application in the bundle: `app1.lua`. But for `app3.lua` we will call `copyAppSrc` function with `appName == app3.lua` and copy `app3.lua`, so there will be two applications instead. We can fix this by updating `appName`, if there is symlink found.

2023-07-13 11:55 UTC, psergee commented on cli/pack/common.go
> +		appName = filepath.Base(appPath)
What will archive name in this case?

2023-07-13 12:23 UTC, DerekBum commented on cli/pack/common.go
> +		appName = filepath.Base(appPath)
Well, it depends on other flags. If we used `--filename` flag, we also specified the name of the archive.
If we specified the package name via `--name` flag, archive will be named as `<name>-<version>.<arch>.tar.gz`.
Else, folder name of the environment will be used as a name in `<name>-<version>.<arch>.tar.gz`.

`copyAppSrc` function has no affect on archive name

2023-07-17 08:32 UTC, psergee commented
- After unpacking with `--strip-components=1`, looks like `tt.yaml` disappears.
- The structure of the archive still differs from `cartridge`. In cartridge archive there is only one directory in root - `<app_name>`. `tt pack` must create the same structure. `tt init` in cartridge application directory will create the desired structure.

2023-07-17 09:25 UTC, psergee commented on test/integration/pack/test_pack.py
> +            "check_exist": [
Need to check that no other files/dirs exist in archive root. Only app name dir.

2023-07-18 08:03 UTC, psergee commented
Manual test:
```
$ tar xf ../app1-0.1.0.0.x86_64.tar.gz --strip-components=1

$ tt start
   • Starting an instance [tmp:s2-master]...
   • Starting an instance [tmp:s2-replica]...
   • Starting an instance [tmp:stateboard]...
   • Starting an instance [tmp:router]...
   • Starting an instance [tmp:s1-master]...
   • Starting an instance [tmp:s1-replica]...

$ tt status
INSTANCE           STATUS          PID
tmp:stateboard     RUNNING         11275
tmp:router         NOT RUNNING     
tmp:s1-master      NOT RUNNING     
tmp:s1-replica     NOT RUNNING     
tmp:s2-master      NOT RUNNING     
tmp:s2-replica     NOT RUNNING
```
Suppose, this is due to app name detection difference in `tt` and `cartridge`. Need to investigate the way cartridge finds out the application name. From the rockspec file probably...

2023-07-18 09:58 UTC, DerekBum commented on cli/pack/common.go
> +				appsToPack += ", which will be named " + packCtx.Name
You need to use `--name` flag with argument, that differs from the application name

2023-07-21 12:31 UTC, psergee approved these changes
lgtm

2023-07-25 14:59 UTC, LeonidVas requested changes
Hi! Thank you for the patch.
Generally ok I only have one nit.

2023-07-26 11:47 UTC, LeonidVas approved these changes

2023-07-26 11:47 UTC, merged