ps ax|grep tarantool showes lua code
tarantool/tt pull request #53
Opened 2022-04-20 00:59 UTC by better0fdead

Previously instance launch code was passed to tarantool
using "-e" flag, so it showed code in ps.
To solve it i passed code through stdin pipe using
"-" flag.

2022-04-20 12:21 UTC, LeonidVas requested changes
Hi! Thank you for the patch.
```
launcher: use "-" flag instead of "-e" to start instance
**// Add a blank line, otherwise it will all be a commit title.**
Previously instance launch code was passed to tarantool
using "-e" flag, so it showed code in ps.
To solve it i passed code through stdin pipe using
"-" flag.
**// Add a blank line to separate this part from the rest of the commit message.**
Close https://github.com/tarantool/tt/issues/37
// Just Close #37
```

2022-04-20 12:21 UTC, LeonidVas commented on cli/running/instance.go
> +	StdinPipe, _ := inst.Cmd.StdinPipe()
Add a check `if err != nil`

2022-04-20 12:32 UTC, LeonidVas commented on cli/running/lua/launcher.lua
>  --- This is a launch script that does the necessary preparation
And an empty line after commit title.

2022-04-20 12:47 UTC, better0fdead commented on cli/running/lua/launcher.lua
>  --- This is a launch script that does the necessary preparation
Ok fixed

2022-04-20 12:48 UTC, better0fdead commented on cli/running/instance.go
> +	StdinPipe, _ := inst.Cmd.StdinPipe()
Added

2022-04-21 09:09 UTC, LeonidVas approved these changes

2022-04-21 09:11 UTC, merged