tt: change working directory
tarantool/tt pull request #633
Opened 2023-10-06 16:13 UTC by psergee

- Change work dir to application source location. In case of single instance application, separate directory will be created in instances enabled directory.
- Re-work application files layout and naming.

Part of #570

2023-10-13 14:56 UTC, better0fdead commented on cli/pack/common.go
> +// prepeareArtifactFilters prepare a slice of filter for runtime artifacts.
```suggestion
// prepeareArtifactFilters prepares a slice of filter for runtime artifacts.
```

2023-10-13 14:58 UTC, better0fdead requested changes
Hi, thx for patch. Please add a Changelog entry and description to the second commit,

2023-10-16 15:56 UTC, LeonidVas approved these changes
Hi! Thank you for the patchset.
LGTM!

2023-10-17 07:34 UTC, psergee commented on cli/pack/common.go
> +// prepeareArtifactFilters prepare a slice of filter for runtime artifacts.
Fixed

2023-10-17 07:47 UTC, psergee commented
> Hi, thx for patch. Please add a Changelog entry and description to the second commit,

The change log notes are about the changes, not commits. `pack` command changes are a part of layout and naming update. Since there are a lot of changes for the `pack`, they are in a separate commit.

2023-10-17 10:22 UTC, better0fdead approved these changes

2023-10-17 10:25 UTC, merged