tt: add tt run module
tarantool/tt pull request #73
Opened 2022-06-07 15:15 UTC by better0fdead

Added module to start instances without watchdog.

Closes #29

2022-06-10 15:52 UTC, LeonidVas requested changes
Hi! Thank you for the patch.
- Add tests
- The `tt run` must be able to run a file (for example, `tt run example.lua`).
- `tt run` must be used to start the instance in `tt start`.
- I think the command should consider the config according to some flag (`--use-cfg`). I think we can use this in `tt start`. In this case, `watchdog` will need to watch for changes in the fields: `restart_on_failure`, `log_dir`. It may also be necessary to pass information to `tt run` (how exactly should be thought about) whether to create a socket and PIDfile or no.

2022-06-14 22:27 UTC, better0fdead commented on cli/cmd/run.go
> +// NewStartCmd creates start command.
Fixed

2022-06-14 22:27 UTC, better0fdead commented on cli/cmd/run.go
> +	var startCmd = &cobra.Command{
Fixed

2022-06-14 22:27 UTC, better0fdead commented on cli/cmd/run.go
> +// internalStartModule is a default start module.
Fixed

2022-06-14 22:27 UTC, better0fdead commented on cli/cmd/run.go
> +		Short: "Start tarantool instance without watchdog",
Fixed

2022-06-14 22:28 UTC, better0fdead commented on cli/running/instance.go
> +		inst.Cmd = exec.Command("tarantool")
Fixed

2022-06-14 22:28 UTC, better0fdead commented on cli/running/instance.go
> +	inst.Cmd.Env = append(inst.Cmd.Env, "TARANTOOLCTL=true")
Fixed

2022-06-16 13:15 UTC, better0fdead commented on CHANGELOG.md
> +- Module ``tt run``, to start tarantool instance without watchdog.
Fixed

2022-06-16 13:16 UTC, better0fdead commented on README.rst
> +* ``run`` - start tarantool instance without watchdog.
Fixed

2022-06-16 13:16 UTC, better0fdead commented on cli/running/instance.go
> +// Run runs tarantool (using script/no script)
Fixed

2022-06-16 13:16 UTC, better0fdead commented on cli/cmd/run.go
> +	return startCmd
Added flag supports

2022-06-16 13:16 UTC, better0fdead commented on cli/cmd/run.go
> +		if err := running.FillCtx(cliOpts, cmdCtx, args); err != nil {
rewrote

2022-07-04 10:49 UTC, better0fdead commented on cli/running/lua/launcher.lua
> +    if os.getenv("DUP2_STATE") then
Added

2022-07-04 10:50 UTC, better0fdead commented on cli/running/instance.go
> +		inst.Cmd.Env = append(inst.Cmd.Env, "DUP2_STATE=true")
Fixed

2022-07-04 10:50 UTC, better0fdead commented on cli/cmd/run.go
> +		Short: "Start tarantool instance",
Fixed

2022-07-04 10:52 UTC, better0fdead commented on cli/cmd/run.go
> +			if !terminal.IsTerminal(syscall.Stdin) {
Added

2022-07-04 10:53 UTC, better0fdead commented on cli/running/instance.go
> +// Run runs tarantool (using script/no script).
Fixed

2022-07-04 10:54 UTC, better0fdead commented on cli/running/running.go
> +// Run starts an Instance (without watchdog).
Changed

2022-07-04 10:55 UTC, better0fdead commented on cli/cmd/run.go
> +	runCmd.Flags().BoolVarP(&flagV, "version", "v", false, "print tarantool version and exit")
Changed

2022-07-04 10:58 UTC, better0fdead commented on cli/running/instance.go
> +		syscall.Dup2(0, 7)
Added

2022-07-04 10:58 UTC, better0fdead commented on cli/running/instance.go
> +	//inst.Cmd.Stdin = os.Stdin
Removed

2022-07-04 11:04 UTC, better0fdead commented on cli/running/instance.go
> +	if pipeFlag {
Fixed

2022-07-04 11:06 UTC, better0fdead commented on cli/running/instance.go
> +	pipeFlag := false
Added

2022-07-04 12:46 UTC, better0fdead commented on cli/cmd/run.go
> +var (
Added

2022-07-04 12:47 UTC, better0fdead commented on cli/cmd/run.go
> +	flagS string
Renamed

2022-07-04 12:47 UTC, better0fdead commented on cli/cmd/run.go
> +func getRunOpts(cmdCtx_t cmdcontext.CmdCtx) *cmdcontext.RunOpts {
Fixed

2022-07-05 12:23 UTC, better0fdead commented on cli/cmdcontext/cmdcontext.go
> +type RunOpts struct {
Moved

2022-07-05 12:23 UTC, better0fdead commented on cli/running/instance.go
> +func (inst *Instance) Run(flags *cmdcontext.RunFlags) error {
Refactored

2022-07-12 20:27 UTC, LeonidVas requested changes
Points from https://github.com/tarantool/tt/pull/73#pullrequestreview-1026093609 are relevant.

Not working scenarios:
* Forwarding of arguments:
![image](https://user-images.githubusercontent.com/57662928/178588056-7203ba12-ead5-4b10-a553-93c60c0ffa15.png)

* Stop an instance with SIGINT
![image](https://user-images.githubusercontent.com/57662928/178588675-f72c296f-7999-4dc2-9851-9968999e7977.png)

2022-07-12 20:27 UTC, LeonidVas commented on cli/running/run_test.go
> +// startTestInstance starts instance for the test.
`startTestInstance` -> `startTestRun`

2022-07-12 20:27 UTC, LeonidVas commented on cli/running/run_test.go
> +		//fmt.Printf(appPath)
Clean the code.

2022-07-12 20:27 UTC, LeonidVas commented on cli/running/run_test.go
> +func TestEflag(t *testing.T) {
Use normal names instead of S,E...

2022-07-15 23:43 UTC, better0fdead commented
> Points from [#73 (review)](https://github.com/tarantool/tt/pull/73#pullrequestreview-1026093609) are relevant.
> 
> Not working scenarios:
> 
> * Forwarding of arguments:
>   ![image](https://user-images.githubusercontent.com/57662928/178588056-7203ba12-ead5-4b10-a553-93c60c0ffa15.png)
> * Stop an instance with SIGINT
>   ![image](https://user-images.githubusercontent.com/57662928/178588675-f72c296f-7999-4dc2-9851-9968999e7977.png)

Fixed

2022-07-15 23:43 UTC, better0fdead commented on test/integration/run/test_run.py
> +def test_running_flag_v(tt_cmd, tmpdir):
Renamed

2022-07-15 23:43 UTC, better0fdead commented on cli/running/run_test.go
> +	r, w, _ := os.Pipe()
Changed

2022-07-15 23:43 UTC, better0fdead commented on cli/running/run_test.go
> +func TestEflag(t *testing.T) {
Changed

2022-07-15 23:43 UTC, better0fdead commented on cli/running/run_test.go
> +// cleanupTestInstance sends a SIGKILL signal to test
Changed

2022-07-15 23:43 UTC, better0fdead commented on cli/running/running.go
> +		if len(appName) > 4 {
Changed

2022-07-15 23:44 UTC, better0fdead commented on cli/running/running.go
> +	if !runFlag {
Changed

2022-07-15 23:44 UTC, better0fdead commented on cli/running/lua/launcher.lua
> +    if os.getenv("TT_DUP2_STATE") then
Changed

2022-07-15 23:44 UTC, better0fdead commented on cli/running/lua/launcher.lua
> +    -- If stdin of the program was moved, then move it back.
Changed

2022-07-15 23:44 UTC, better0fdead commented on cli/running/instance.go
> +		inst.Cmd.Env = append(inst.Cmd.Env, "TT_DUP2_STATE=false")
Changed

2022-07-15 23:44 UTC, better0fdead commented on test/integration/run/test_app/test_app.lua
> +print(123)
Changed

2022-07-15 23:44 UTC, better0fdead commented on cli/running/run_test.go
> +// startTestInstance starts instance for the test.
Changed

2022-07-15 23:44 UTC, better0fdead commented on cli/running/run_test.go
> +		//fmt.Printf(appPath)
Cleaned

2022-07-15 23:44 UTC, better0fdead commented on cli/running/running.go
> +func FillCtx(cliOpts *config.CliOpts, cmdCtx *cmdcontext.CmdCtx, args []string, runFlag bool) error {
Done

2022-07-15 23:44 UTC, better0fdead commented on cli/running/instance.go
> +	// pipeFlag is a flag used to indicate whether stdin should be moved or not.
Changed

2022-07-15 23:48 UTC, better0fdead commented
[#1](https://github.com/tarantool/tt/pull/73#discussion_r919028513) Added comment
[#2](https://github.com/tarantool/tt/pull/73#discussion_r919029819) I can explain it in call, in shortly it is needed because in case when we need to find app file we need already run0pts.
[#3](https://github.com/tarantool/tt/pull/73#discussion_r919057585) Changed

2022-07-19 10:52 UTC, LeonidVas requested changes
Hi! Thank you for the patchset.
The code already looks worthy.
The case when the code does not work correctly:
```
┌─[leonid@vasya-hp]─[~/work/mail/tt]
└──╼ cat test_2.lua 
print(arg[1])
┌─[leonid@vasya-hp]─[~/work/mail/tt]
└──╼ cat test_2.lua | tarantool - --my-app-option
--my-app-option
┌─[leonid@vasya-hp]─[~/work/mail/tt]
└──╼ cat test_2.lua | ./tt run - --my-app-option
unknown flag: --my-app-option

Usage: tt run [flags] 

```

2022-07-19 10:52 UTC, LeonidVas commented on cli/cmdcontext/cmdcontext.go
> +	// CommandName contains name of the command
Set a dot at the end of the sentence.

2022-07-19 10:52 UTC, LeonidVas commented on cli/running/running.go
> +func FillCtx(cliOpts *config.CliOpts, cmdCtx *cmdcontext.CmdCtx,
Unnecessary changes.

2022-07-19 10:52 UTC, LeonidVas commented on cli/running/run_test.go
> +	r, w, _ := os.Pipe()
Do not use one-letter names,

2022-07-19 10:52 UTC, LeonidVas commented on cli/running/run_test.go
> +	r, w, _ := os.Pipe()
Do not use one-letter names,

2022-07-19 10:52 UTC, LeonidVas commented on cli/running/run_test.go
> +	r, w, _ := os.Pipe()
Do not use one-letter names,

2022-07-19 10:52 UTC, LeonidVas commented on cli/running/run_test.go
> +	r, w, _ := os.Pipe()
Do not use one-letter names,

2022-07-19 10:52 UTC, LeonidVas commented on test/integration/run/test_app/test_app.lua
> +print('Instance running!')
![image](https://user-images.githubusercontent.com/57662928/179732808-d2304dea-9042-41eb-93d8-e367bbdf398b.png)

2022-07-19 10:54 UTC, LeonidVas commented
If any commit comes after the closing commit, it is `Follow ups #', not `Part of #'.
![image](https://user-images.githubusercontent.com/57662928/179733887-e056d905-48ce-4bf0-a387-2db0554be4c0.png)

2022-07-19 13:17 UTC, better0fdead commented on cli/cmdcontext/cmdcontext.go
> +	// CommandName contains name of the command
Done

2022-07-19 13:17 UTC, better0fdead commented on cli/running/running.go
> +func FillCtx(cliOpts *config.CliOpts, cmdCtx *cmdcontext.CmdCtx,
It is for new linter.(line is too long)

2022-07-19 13:18 UTC, better0fdead commented on cli/running/run_test.go
> +	r, w, _ := os.Pipe()
Done

2022-07-19 13:18 UTC, better0fdead commented on cli/running/run_test.go
> +	r, w, _ := os.Pipe()
Done

2022-07-19 13:18 UTC, better0fdead commented on cli/running/run_test.go
> +	r, w, _ := os.Pipe()
Done

2022-07-19 13:18 UTC, better0fdead commented on cli/running/run_test.go
> +	r, w, _ := os.Pipe()
Done

2022-07-19 13:18 UTC, better0fdead commented
> If any commit comes after the closing commit, it is `Follow ups #', not `Part of #'.
> ![image](https://user-images.githubusercontent.com/57662928/179733887-e056d905-48ce-4bf0-a387-2db0554be4c0.png)
Fixed

2022-07-19 13:20 UTC, better0fdead commented
> Hi! Thank you for the patchset. The code already looks worthy. The case when the code does not work correctly:
> 
> ```
> ┌─[leonid@vasya-hp]─[~/work/mail/tt]
> └──╼ cat test_2.lua 
> print(arg[1])
> ┌─[leonid@vasya-hp]─[~/work/mail/tt]
> └──╼ cat test_2.lua | tarantool - --my-app-option
> --my-app-option
> ┌─[leonid@vasya-hp]─[~/work/mail/tt]
> └──╼ cat test_2.lua | ./tt run - --my-app-option
> unknown flag: --my-app-option
> 
> Usage: tt run [flags] 
> ```

Added comment about it in help of command.

2022-07-19 13:45 UTC, LeonidVas approved these changes
LGTM.

2022-07-19 13:45 UTC, merged