Release 2.5.0
tarantool/tt pull request #984
Opened 2024-10-15 13:16 UTC by dmyger

Added a number of subcommands for replicaset roles, improved understanding of the version number to install, enhanced status display, and added a flag to disable interactivity when the application is stopped.
Implemented a number of fixes to improve stability.

### Added

- `tt status`: display `config`, `box`, and `replication upstream` statuses.
  * `--details`: display detailed reports of errors and warnings from instances.
- `tt stop` confirmation prompt. `-y` option is added to accept stop without prompting.
- `tt cluster replicaset roles add`: command to add roles in config scope provided by flags.
- `tt replicaset roles remove`: command to remove roles in the tarantool replicaset with cluster config (3.0) or cartridge orchestrator.
- `tt replicaset roles add`: command to add roles in the tarantool replicaset with cluster config (3.0) or cartridge orchestrator.
- `tt replicaset roles remove`: command to remove roles in the tarantool replicaset with cluster config (3.0) or cartridge orchestrator.
- `tt install tt|tarantool <version>` - allow `<version>` be incomplete. So `2.3` will install the the last available release with specified `<major=2>.<minor=3>` in `<version>`.

### Fixed

- Command `\set delimiter [marker]` works correctly and don't hangs `tt` console.
- `tt log -f` crash on removing log directory.
- `tt connect` crash due to an empty response.
- `tt start` error on start Tarantool 3 with encrypted etcd.
- `tt replicaset vshard bootstrap` unable to bootstrap large clusters due to a timeout.
- `tt replicaset vshard bootstrap` timeout was 3s instead of 10s.

2024-10-15 21:08 UTC, oleg-jukovec commented
We unify a release procedure a bit for out team:

https://github.com/tarantool/ecosystem-team/pull/58

1. Please, add a small description to the release to the release commit.
2. Change the release commit message to `Release 2.5.0` instead of release notes.
3. Make beautiful formatting for PR, since it will be used as a release notes on GitHub (I've done it just as example).

2024-10-15 21:09 UTC, oleg-jukovec requested changes
We unify a release procedure a bit for out team:

https://github.com/tarantool/ecosystem-team/pull/58

1. Please, add a small description to the release to the release commit.
2. Change the release commit message to `Release 2.5.0` instead of release notes.
3. Make beautiful formatting for PR, since it will be used as a release notes on GitHub (I've done it just as example).

2024-10-16 10:35 UTC, oleg-jukovec commented on CHANGELOG.md
> +
A short description should be added here too.

2024-10-16 11:33 UTC, oleg-jukovec approved these changes

2024-10-16 12:46 UTC, DerekBum approved these changes

2024-10-16 13:22 UTC, merged