tests: fix flacky test_running_base_functionality
tarantool/tt pull request #992
Opened 2024-10-21 12:59 UTC by themilchenko

The integration test `test_running_cluster::test_running_base_functionality` fails sometimes with an failed assertion of the same PID after restart.

After the patch waiting for instances stop was added to make sure that cluster is down before it will start again and will check for PID.

Closes #972

2024-10-21 13:10 UTC, oleg-jukovec requested changes
I think it is possible that some instance already restarted and we will wait for stopping of a new PID.

It looks we need to collect active PIDs before restart and wait until it stopped.

2024-10-22 17:00 UTC, themilchenko commented
> I think it is possible that some instance already restarted and we will wait for stopping of a new PID.
> 
> It looks we need to collect active PIDs before restart and wait until it stopped.

Added check for it.

2024-10-22 18:17 UTC, oleg-jukovec commented
> > I think it is possible that some instance already restarted and we will wait for stopping of a new PID.
> > It looks we need to collect active PIDs before restart and wait until it stopped.
> 
> Added check for it.

I think it should looks like:

1. Collect all instances pids.
2. Call `tt restart`.
3. Wait for the pids.

2024-10-23 10:11 UTC, oleg-jukovec commented
> Now we read a PID file (if it is exists, because it can be already deleted) after restart, check that PID is the same as collected one after first start and if so wait for the instance will stop completely. What am I missing?

Oh, it's my fault. I've missed that we wait for pids from `pidByInstanceName` that was fetched after start and before restart. In this case we could just wait for pids from `pidByInstanceName` without additional checks.

2024-10-23 11:21 UTC, themilchenko commented
> > Now we read a PID file (if it is exists, because it can be already deleted) after restart, check that PID is the same as collected one after first start and if so wait for the instance will stop completely. What am I missing?
> 
> Oh, it's my fault. I've missed that we wait for pids from `pidByInstanceName` that was fetched after start and before restart. In this case we could just wait for pids from `pidByInstanceName` without additional checks.

Done.

2024-10-23 18:32 UTC, oleg-jukovec approved these changes

2024-10-24 10:59 UTC, dmyger commented on test/utils.py
> +        with open(file, "r") as f:
Question: when the instance stopped a file `tarantool.pid` keeps on filesystem?
It seems, that if no a such file, retries for this function will takes 20 seconds.

2024-10-24 10:59 UTC, dmyger commented on test/integration/running/test_running_cluster.py
> +            wait_pid_disappear(os.path.join(run_dir, inst, 'tarantool.pid'),
May be better read all pids in `list` and wait all at once?

2024-10-28 13:21 UTC, dmyger approved these changes

2024-10-28 14:18 UTC, merged